project:
  type: website
  output-dir: docs

website:
  title: "Vignesh Gopakumar"
  favicon: Images/dy_dx.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - talks.qmd
      - Blog/blog.qmd
  page-footer:
    left: "© Copyright 2026 Vignesh Gopakumar"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: false
    page-layout: full
