project:
  type: website

website:
  title: "Vignesh Gopakumar"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - publications.qmd
      - talks.qmd
      - blog.qmd
  page-footer:
    left: "© Copyright 2024 Vignesh Gopakumar"
format:
  html:
    theme: solar
    css: styles.css
    toc: false
    page-layout: full