project:
  type: website
  output-dir: docs

website:
  title: "Vignesh Gopakumar"
  favicon: Images/dy_dx.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - talks.qmd
      - blog.qmd
  page-footer:
    left: "© Copyright 2025 Vignesh Gopakumar"
format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    page-layout: full
