---
title: "Publications"
format: html
---
<style>
.btn {
  display: inline-block;
  padding: 6px 12px;
  margin-bottom: 0;
  font-size: 14px;
  font-weight: 400;
  line-height: 1.42857143;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  cursor: pointer;
  border: 1px solid transparent;
  border-radius: 4px;
  text-decoration: none;
}
.btn-paper {
  color: #fff;
  background-color: #007bff;
  border-color: #007bff;
}
.btn-code {
  color: #fff;
  background-color: #28a745;
  border-color: #28a745;
}
</style>

***

### Highlighted Publications 

- **Uncertainty Quantification of Pre-Trained and Fine-Tuned Surrogate Models using Conformal Prediction**
  - Authors: Gopakumar, Vignesh; Gray, Ander; Oskarsson, Joel; Zanisi, Lorenzo; Pamela, Stanislas; Giles, Daniel; Kusner, Matt; Deisenroth, Marc
  - Published in: arXiv preprint arXiv:2408.09881, 2024
  - TLDR: [Brief summary of the paper]
  - [<span class="btn btn-paper">Paper</span>](https://arxiv.org/abs/2408.09881) [<span class="btn btn-code">Code</span>](https://github.com/gitvicky/Spatio-Temporal-CP)


- **Valid Error Bars for Neural Weather Models using Conformal Prediction**
  - Authors: Gopakumar, Vignesh; Oskarsson, Joel; Gray, Ander; Zanisi, Lorenzo; Pamela, Stanislas; Giles, Daniel; Kusner, Matt; Deisenroth, Marc
  - Published in: arXiv preprint arXiv:2406.14483, 2024
  - TLDR: [Brief summary of the paper]
  - [<span class="btn btn-paper">Paper</span>](https://arxiv.org/abs/2406.14483) [<span class="btn btn-code">Code</span>](https://github.com/gitvicky/neural-lam-CP)


- **Plasma surrogate modelling using Fourier neural operators**
  - Authors: Gopakumar, Vignesh; Pamela, Stanislas; Zanisi, Lorenzo; Li, Zongyi; Gray, Ander; Brennand, Daniel; Bhatia, Nitesh; Stathopoulos, Gregory; Kusner, Matt; Deisenroth, Marc
  - Published in: Nuclear Fusion, Volume 64, Number 5, 2024
  - TLDR: [Brief summary of the paper]
  - [<span class="btn btn-paper">Paper</span>](https://iopscience.iop.org/article/10.1088/1741-4326/ad313a/meta) [<span class="btn btn-code">Code</span>](https://github.com/Plasma-FNO)

- **Loss landscape engineering via data regulation on PINNs**
  - Authors: Gopakumar, Vignesh; Pamela, Stanislas; Samaddar, Debasmita
  - Published in: Machine Learning with Applications, Volume 12, 2023
  - TLDR: [Brief summary of the paper]
  - [<span class="btn btn-paper">Paper</span>](https://www.sciencedirect.com/science/article/pii/S2666827023000178) [<span class="btn btn-code">Code</span>](https://github.com/gitvicky/Loss_Landscape_PINNs)

- **Fourier-RNNs for modelling noisy physics data**
  - Authors: Gopakumar, Vignesh; Pamela, Stanislas; Zanisi, Lorenzo
  - Published in: arXiv preprint arXiv:2302.06534, 2023
  - TLDR: [Brief summary of the paper]
  - [<span class="btn btn-paper">Paper</span>](https://arxiv.org/abs/2302.06534)

- **Image mapping the temporal evolution of edge characteristics in tokamaks using neural networks**
  - Authors: Gopakumar, Vignesh; Samaddar, Debasmita
  - Published in: Machine Learning: Science and Technology, Volume 1, Number 1, 2020
  - TLDR: [Brief summary of the paper]
  - [<span class="btn btn-paper">Paper</span>](https://iopscience.iop.org/article/10.1088/2632-2153/ab5639/meta) 

### Other Publications

- **Neural-Parareal: Self-Improving Acceleration of Fusion MHD Simulations Using Time-Parallelisation and Neural Operators**
  - Authors: Pamela, SJP; Carey, N; Brandstetter, J; Akers, R; Zanisi, L; Buchanan, J; Gopakumar, V; Hoelzl, M; Huijsmans, G; Pentland, K
  - Published in: Computer Physics Communications, 2024
  - TLDR: [Brief summary of the paper]
  - [Paper](https://www.sciencedirect.com/science/article/abs/pii/S001046552400314X) 

- **Data efficiency and long term prediction capabilities for neural operator surrogate models of core and edge plasma codes**
  - Authors: Carey, N; Zanisi, L; Pamela, S; Gopakumar, V; Omotani, J; Buchanan, J; Brandstetter, J
  - Published in: arXiv preprint arXiv:2402.08561, 2024
  - TLDR: [Brief summary of the paper]
  - [Paper](https://arxiv.org/abs/2402.08561)


- **Efficient training sets for surrogate models of tokamak turbulence with active deep ensembles**
  - Authors: Zanisi, L; Ho, A; Barr, J; Madula, T; Citrin, J; Pamela, S; Buchanan, J; Casson, FJ; Gopakumar, V; Contributors, JET
  - Published in: Nuclear Fusion, Volume 64, Number 3, 2024
  - TLDR: [Brief summary of the paper]
  - [Paper](https://iopscience.iop.org/article/10.1088/1741-4326/ad240d/meta)

- **Multi-Objective Bayesian Optimization for Design of Pareto-Optimal Current Drive Profiles in STEP**
  - Authors: Brown, Theodore; Marsden, Stephen; Gopakumar, Vignesh; Terenin, Alexander; Ge, Hong; Casson, Francis
  - Published in: IEEE Transactions on Plasma Science, 2024
  - TLDR: [Brief summary of the paper]
  - [Paper](https://ieeexplore.ieee.org/abstract/document/10507168)

- **Overview of the EUROfusion Tokamak Exploitation programme in support of ITER and DEMO**
  - Authors: Joffrin, Emmanuel Henri; Wischmeier, Marco; Baruzzo, Matteo; Hakola, Antti; Kappatou, Athina; Keeling, David; Labit, Benoit; Tsitrone, Emmanuelle; Vianello, Nicola
  - Published in: Nuclear Fusion, 2023
  - TLDR: [Brief summary of the paper]
  - [Paper](https://iopscience.iop.org/article/10.1088/1741-4326/ad2be4/meta)

- **Spatio-temporal forecasting of plasma turbulence using deep learning**
  - Authors: Gaur, Rahul; Gopakumar, Vignesh; Barbour, Nathaniel; Jang, Byoungchan; Mandell, Noah; Abel, Ian; Dorland, William; Kolemen, Egemen
  - Presented at: APS Division of Plasma Physics Meeting Abstracts, 2023
  - TLDR: [Brief summary of the paper]
  - [Link to the presentation](https://ui.adsabs.harvard.edu/abs/2023APS..DPPJO9015G/abstract)

- **Fast regression of the tritium breeding ratio in fusion reactors**
  - Authors: Mánek, Petr; Van Goffrier, Graham; Gopakumar, Vignesh; Nikolaou, Nikolaos; Shimwell, Jonathan; Waldmann, Ingo
  - Published in: Machine Learning: Science and Technology, Volume 4, Number 1, 2023
  - TLDR: [Brief summary of the paper]
  - [Paper](https://iopscience.iop.org/article/10.1088/2632-2153/acb2b3/meta)

- **Shaping of Magnetic Field Coils in Fusion Reactors using Bayesian Optimisation**
  - Authors: Nunn, Timothy; Authority, UK Atomic Energy; Gopakumar, Vignesh; Kahn, Sebastien
  - Published in: Bayesian Optimisation Workshop @ NeurIPS 2022
  - TLDR: [Brief summary of the paper]
  - [Paper](https://arxiv.org/abs/2310.01455)

- **Development of fusion reactor digital twins in the Metaverse**
  - Authors: Margetts, Lee; Akers, Rob; Ghosh, Abhijeet; Gopakumar, Vignesh; Hadorn, Patrik; Hummel, Mathias; Messmer, Peter; Omer, Muhammad; Ozturk, Ekin; Pamela, Stanislav
  - Published in: IET Nuclear Engineering for Safety, Control and Security, 2022
  - TLDR: [Brief summary of the paper]
  - [Paper](https://digital-library.theiet.org/content/journals/10.1049/nse2.12066)

- **Active and continual learning of fusion plasma turbulence surrogate models for digital twinning of a tokamak device**
  - Authors: Barr, Jackson; Madula, Thandikire; Zanisi, Lorenzo; Gopakumar, Vignesh; Ho, Aaron; Citrin, Jonathan; Contributors, and JET
  - Presented at: ReALML@ICML, 2022
  - TLDR: [Brief summary of the paper]
  - [Paper](https://realworldml.github.io/files/cr/paper24.pdf)


- **14 MeV neutron irradiation experiments-gamma spectroscopy analysis and validation automation**
  - Authors: Stainer, Thomas; Gilbert, Mark R; Packer, Lee W; Lilley, Steven; Gopakumar, Vignesh; Wilson, Chris
  - Published in: EPJ Web of Conferences, Volume 247, 2021
  - TLDR: [Brief summary of the paper]
  - [Paper](https://doi.org/10.1051/epjconf/202124709010)

- **Informed Sampling of the Plasma Hyperspace for Digital Twinning**
  - Authors: Bakrania, Mayur; Gopkakumar, Vignesh
  - Presented at: IAEA Technical Meeting on Fusion Data Processing, Validation, Analysis, 2021
  - TLDR: [Brief summary of the paper]
  - [Paper](https://conferences.iaea.org/event/251/)

